# -*- coding: utf-8 -*-
"""Day_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9BYnvnXLtrfpIdle2swVW-VxR1oHJcc
"""

#1
"""Check Data Type of a Variable
Write a program to check the data type of a given variable."""
a=1
b=1.1
c=1j
print("Type of a variable",type(a))
print("Type of b variable",type(b))
print("Type of c variable",type(c))

#2
"""Convert String to Integer
Write a program to input a string and convert it to an integer, then print the result."""
x=float(1.2)
y=int(1)
z=float("3")
z1=int("3")
print("value of a x :",x)
print("value of a y :",y)
print("value of a z :",z)
print("value of a z1 :",z1)

#3
"""Concatenate Integer and String
Write a program to concatenate an integer and a string after converting the integer to a string."""
x=12
z="string"
int_str=str(x)
concate_ans=int_str+z
print("The concatenated ans is :",concate_ans)

#4
"""Find Length of a String
Write a program to input a string and find its length"""
my_str=input("enter your string")
print(my_str)
print("length of a string is : ",len(my_str))

#5
"""Convert Float to Integer
Write a program to input a float value, convert it to an integer, and print the result."""
num=10.8
num=int(num)
print("converted float in a integer : ",num)

#using a user input
num=input("Enter a float value")
num=float(num)
int_num=int(num)
print("convertaed flaot in a integer :",int_num)

#6
"""Sum of Two Float Numbers
Write a program to input two float numbers, add them, and print the result."""
num1 = input("enter a float value num1")
num2 = input("enter a flaot value num2")
add = num1+num2
print(add)

#7
"""Check if a String is Numeric
Write a program to check if a given string is numeric"""

string="123"
ans = string.isnumeric()
print(ans)

#8
"""Convert List to Tuple
Write a program to convert a list of numbers to a tuple."""
lis = [1,2,3,4,5,6]
convert_tuple=tuple(lis)
print(convert_tuple)

#9
"""Sum of Digits in a String
Write a program to input a string of numbers, extract each digit, convert them to integers, and find their sum."""
number1 = input("Enter a string of number1-")
number2 = input("Enter a string of number2-")
number1=str(number1)
number2=str(number2)
a=int(number1)
b=int(number2)
sum = a-b
print(sum)

#10
"""Concatenate List and Tuple
Write a program to concatenate a list and a tuple, after converting the tuple to a list."""
my_list=[1,2,3]
my_tuple=(4,5,6)

my_tuple_list=list(my_tuple)

result=my_list+my_tuple_list
print(result)