# -*- coding: utf-8 -*-
"""Day_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhQXBpIgWkzPZ_gC50FQ2y6BhDKjDwQL
"""

#1
"""Print Function: Write a Python program that prints your name and age using the print function."""
name = "Sonali"
age = 21
print("My Name is ", name)
print("My Age is ", age)

#2
"""Single-Line Comment: Create a Python program that uses a single-line comment to explain what the program does before printing a message to the user."""
# This program print the addition of two numbers
a = 10
b = 20
add  = a+b
print("Addition of two number :",add)

#3
"""Multi-Line Comment: Write a Python script that uses a multi-line comment to describe the purpose of the script and then prints "Hello, World!"."""
"""Since Python will ignore string literals that are not assigned to a variable, you can  add a multiline string (triple quotes) in your code,
and place your comment inside it: this code print a hello world"""

print("Hello, World!")

#4
"""Variables: Define a variable called favorite_color and assign it your favorite color. Then, print a message that includes this variable."""
favorite_color =  "blue"
print("My fav color is", favorite_color)

#5
"""Data Types: Create a program that defines variables of different data types (integer, float, string, and boolean) and
prints their values along with their types using the type() function"""
# from operator import truediv

a=1
b=1.1
c=1j
d = "sonali"
e=True
f=10>9
print(a, " type of a = ",type(a))
print(b, " type of b = ",type(b))
print(c, " type of c = ",type(c))
print(d, " type of d = ",type(d))
print(e, " type of e = ",type(e))
print(f, " type of f = ",type(f))

#6
"""String Concatenation: Write a Python program that concatenates two string variables (e.g.,first_name and last_name) and prints the full name"""

first_name="sonali"
last_name="phad"
print(first_name +" "+ last_name)

#7
"""Variable Reassignment: Define a variable called score with an initial value of 10, print it, then reassign it to 20, and print it again."""
score = 10
print("Initial value",score)
score = 20
print("Reassign value",score)

#8
"""User Input: Create a program that prompts the user for their age, stores it in a variable, and then prints a message saying how old they are"""

age = input("Enter your age:")
print("You are" ,age,"year old")

#9
"""Boolean Variables: Define a boolean variable called is_student and assign it True. Write a print statement that states whether you are a student or not."""
student = True
if student:
    print("You are a student")
else:
    print("You are not a student")

#10
"""
Simple Calculation
: Write a program that defines two integer variables,
a and b , and prints their sum, difference, product, and quotient.
"""
#addition
a = 10
b = 30
sum = a + b
print("The sum of a and b is",sum)

#Difference
difference = a - b
print("The difference of a and b",difference)

#Product
product = a * b
print("The product of a and b",product)

#Quotient
quotient = a / b
print("The quotient of a and b",quotient)